name: New Relic PR Marker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  log-deployment-marker:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON Payload
        run: |
          # We use a 'here-doc' to create the JSON file safely
          cat <<EOF > payload.json
          {
            "query": "mutation { changeTrackingCreateDeployment(deployment: { entityGuid: \"MjAzMzUwOHxBUE18QVBQTElDQVRJT058OTkzOTAwNjcz\", version: \"${{ github.event.pull_request.head.sha }}\", description: \"PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}\", user: \"${{ github.actor }}\", deploymentType: OTHER, changelog: \"${{ github.event.pull_request.html_url }}\" }) { deploymentId } }"
          }
          EOF

      - name: Send Marker to New Relic
        run: |
          curl -X POST https://api.newrelic.com/graphql \
            -H "Content-Type: application/json" \
            -H "Api-Key: ${{ secrets.NEW_RELIC_USER_KEY }}" \
            --data @payload.json
